name: medit
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pytorch
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - "scipy<1.13"
  - scikit-learn
  - scvi-tools
  - anndata
  - scanpy>=1.9
  - h5py
  - pyarrow
  - numba
  - umap-learn
  - leidenalg
  - statsmodels
  - matplotlib
  - seaborn
  - scikit-misc

  - pip:
      - phate
      - mypy
      - types-requests
      - rich
      - tqdm
